apiVersion: v1
kind: Service
metadata:
  name: react-kubernetes-service
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: http
    targetPort: 30080
  selector:
    app: app
---
apiVersion: apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-kubernetes-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: deploy-react-kubernetes
        image: acrjavaeastus.azurecr.io/react:React148
        ports:
        - containerPort: 3000
